server:
  port: 8092

publisher:
  enabled: true
  topicName: "news/sport/football"

spring:
  main:
    allow-bean-definition-overriding: true

management:
  health:
    jms:
      enabled: true

solace:
  jms:
    host: localhost:55554
    msg-vpn: default
    client-username: admin
    client-password: admin
    clientName: spring-boot-pub
